CTFd/auth.py
from flask import (
    current_app as app,
    render_template,
    request,
    redirect,
    url_for,
    session,
    Blueprint,
)
from CTFd.models import db, Users, Teams

from CTFd.utils import get_config, get_app_config
from CTFd.utils.decorators import ratelimit
from CTFd.utils import user as current_user
from CTFd.utils import config, validators
from CTFd.utils import email
from CTFd.utils.security.auth import login_user, logout_user
from CTFd.utils.security.passwords import hash_password, check_password
from CTFd.utils.logging import log
from CTFd.utils.decorators.visibility import check_registration_visibility
from CTFd.utils.modes import TEAMS_MODE, USERS_MODE
from CTFd.utils.security.signing import serialize, unserialize, SignatureExpired, BadSignature, BadTimeSignature
from CTFd.utils.helpers import info_for, error_for, get_errors, get_infos
from CTFd.utils.config.visibility import registration_visible

import base64
import requests

auth = Blueprint('auth', __name__)


@auth.route('/confirm', methods=['POST', 'GET'])
@auth.route('/confirm/<data>', methods=['GET'])
@ratelimit(method="POST", limit=10, interval=60)
def confirm(data=None):
    if not get_config('verify_emails'):
        # If the CTF doesn't care about confirming email addresses then redierct to challenges
        return redirect(url_for('challenges.listing'))

    # User is confirming email account
    if data and request.method == "GET":
        try:
            user_email = unserialize(data, max_age=1800)
        except (BadTimeSignature, SignatureExpired):
            return render_template('confirm.html', errors=['Your confirmation link has expired'])
        except (BadSignature, TypeError, base64.binascii.Error):
            return render_template('confirm.html', errors=['Your confirmation token is invalid'])

        user = Users.query.filter_by(email=user_email).first_or_404()
        user.verified = True
        log('registrations', format="[{date}] {ip} - successful confirmation for {name}", name=user.name)
        db.session.commit()
        db.session.close()
        if current_user.authed():
            return redirect(url_for('challenges.listing'))
        return redirect(url_for('auth.login'))

    # User is trying to start or restart the confirmation flow
    if not current_user.authed():
        return redirect(url_for('auth.login'))

    user = Users.query.filter_by(id=session['id']).first_or_404()
    if user.verified:
        return redirect(url_for('views.settings'))

    if data is None:
        if request.method == "POST":
            # User wants to resend their confirmation email
            email.verify_email_address(user.email)
            log('registrations', format="[{date}] {ip} - {name} initiated a confirmation email resend")
            return render_template('confirm.html', user=user, infos=['Your confirmation email has been resent!'])
        elif request.method == "GET":
            # User has been directed to the confirm page
            return render_template('confirm.html', user=user)


@auth.route('/reset_password', methods=['POST', 'GET'])
@auth.route('/reset_password/<data>', methods=['POST', 'GET'])
@ratelimit(method="POST", limit=10, interval=60)
def reset_password(data=None):
    if data is not None:
        try:
            name = unserialize(data, max_age=1800)
        except (BadTimeSignature, SignatureExpired):
            return render_template('reset_password.html', errors=['Your link has expired'])
        except (BadSignature, TypeError, base64.binascii.Error):
            return render_template('reset_password.html', errors=['Your reset token is invalid'])

        if request.method == "GET":
            return render_template('reset_password.html', mode='set')
        if request.method == "POST":
            user = Users.query.filter_by(name=name).first_or_404()
            user.password = request.form['password'].strip()
            db.session.commit()
            log('logins', format="[{date}] {ip} -  successful password reset for {name}", name=name)
            db.session.close()
            return redirect(url_for('auth.login'))

    if request.method == 'POST':
        email_address = request.form['email'].strip()
        team = Users.query.filter_by(email=email_address).first()

        errors = get_errors()

        if config.can_send_mail() is False:
            return render_template(
                'reset_password.html',
                errors=['Email could not be sent due to server misconfiguration']
            )

        if not team:
            return render_template(
                'reset_password.html',
                errors=['If that account exists you will receive an email, please check your inbox']
            )

        email.forgot_password(email_address, team.name)

        return render_template(
            'reset_password.html',
            errors=['If that account exists you will receive an email, please check your inbox']
        )
    return render_template('reset_password.html')


@auth.route('/register', methods=['POST', 'GET'])
@check_registration_visibility
@ratelimit(method="POST", limit=10, interval=5)
def register():
    errors = get_errors()
    if request.method == 'POST':
        name = request.form['name']
        email_address = request.form['email']
        password = request.form['password']

        name_len = len(name) == 0
        names = Users.query.add_columns('name', 'id').filter_by(name=name).first()
        emails = Users.query.add_columns('email', 'id').filter_by(email=email_address).first()
        pass_short = len(password) == 0
        pass_long = len(password) > 128
        valid_email = validators.validate_email(request.form['email'])
        team_name_email_check = validators.validate_email(name)

        if not valid_email:
            errors.append("Please enter a valid email address")
        if email.check_email_is_whitelisted(email_address) is False:
                errors.append(
                    "Only email addresses under {domains} may register".format(
                        domains=get_config('domain_whitelist')
                    )
                )
        if names:
            errors.append('That team name is already taken')
        if team_name_email_check is True:
            errors.append('Your team name cannot be an email address')
        if emails:
            errors.append('That email has already been used')
        if pass_short:
            errors.append('Pick a longer password')
        if pass_long:
            errors.append('Pick a shorter password')
        if name_len:
            errors.append('Pick a longer team name')

        if len(errors) > 0:
            return render_template(
                'register.html',
                errors=errors,
                name=request.form['name'],
                email=request.form['email'],
                password=request.form['password']
            )
        else:
            with app.app_context():
                user = Users(
                    name=name.strip(),
                    email=email_address.lower(),
                    password=password.strip()
                )
                db.session.add(user)
                db.session.commit()
                db.session.flush()

                login_user(user)

                if config.can_send_mail() and get_config('verify_emails'):  # Confirming users is enabled and we can send email.
                    log('registrations', format="[{date}] {ip} - {name} registered (UNCONFIRMED) with {email}")
                    email.verify_email_address(user.email)
                    db.session.close()
                    return redirect(url_for('auth.confirm'))
                else:  # Don't care about confirming users
                    if config.can_send_mail():  # We want to notify the user that they have registered.
                        email.sendmail(
                            request.form['email'],
                            "You've successfully registered for {}".format(get_config('ctf_name'))
                        )

        log('registrations', "[{date}] {ip} - {name} registered with {email}")
        db.session.close()
        return redirect(url_for('challenges.listing'))
    else:
        return render_template('register.html', errors=errors)


@auth.route('/login', methods=['POST', 'GET'])
@ratelimit(method="POST", limit=10, interval=5)
def login():
    errors = get_errors()
    if request.method == 'POST':
        name = request.form['name']

        # Check if the user submitted an email address or a team name
        if validators.validate_email(name) is True:
            user = Users.query.filter_by(email=name).first()
        else:
            user = Users.query.filter_by(name=name).first()

        if user:
            if user and check_password(request.form['password'], user.password):
                session.regenerate()

                login_user(user)
                log('logins', "[{date}] {ip} - {name} logged in")

                db.session.close()
                if request.args.get('next') and validators.is_safe_url(request.args.get('next')):
                    return redirect(request.args.get('next'))
                return redirect(url_for('challenges.listing'))

            else:
                # This user exists but the password is wrong
                log('logins', "[{date}] {ip} - submitted invalid password for {name}")
                errors.append("Your username or password is incorrect")
                db.session.close()
                return render_template('login.html', errors=errors)
        else:
            # This user just doesn't exist
            log('logins', "[{date}] {ip} - submitted invalid account information")
            errors.append("Your username or password is incorrect")
            db.session.close()
            return render_template('login.html', errors=errors)
    else:
        db.session.close()

CTFd/views.py
from flask import current_app as app, render_template, request, redirect, abort, url_for, session, Blueprint, Response, send_file
from flask.helpers import safe_join

from CTFd.models import db, Admins, Files, Pages, Notifications
from CTFd.utils import markdown
from CTFd.cache import cache
from CTFd.utils import get_config, set_config
from CTFd.utils.user import authed, get_current_user
from CTFd.utils import config
from CTFd.utils.uploads import get_uploader
from CTFd.utils.config.pages import get_page
from CTFd.utils.config.visibility import challenges_visible
from CTFd.utils.security.auth import login_user
from CTFd.utils.security.csrf import generate_nonce
from CTFd.utils import user as current_user
from CTFd.utils.dates import ctf_started, ctftime
from CTFd.utils.decorators import authed_only
from sqlalchemy.exc import IntegrityError
import os


views = Blueprint('views', __name__)


@views.route('/setup', methods=['GET', 'POST'])
def setup():
    if not config.is_setup():
        if not session.get('nonce'):
            session['nonce'] = generate_nonce()
        if request.method == 'POST':
            ctf_name = request.form['ctf_name']
            set_config('ctf_name', ctf_name)

            # CSS
            set_config('start', '')

            # Admin user
            name = request.form['name']
            email = request.form['email']
            password = request.form['password']
            admin = Admins(
                name=name,
                email=email,
                password=password,
                type='admin',
                hidden=True
            )

            user_mode = request.form['user_mode']

            set_config('user_mode', user_mode)

            # Index page

            index = """<div class="row">
    <div class="col-md-6 offset-md-3">
        <img class="w-100 mx-auto d-block" style="max-width: 500px;padding: 50px;padding-top: 14vh;" src="themes/core/static/img/logo.png" />
        <h3 class="text-center">
            <p>A cool CTF platform from <a href="https://ctfd.io">ctfd.io</a></p>
            <p>Follow us on social media:</p>
            <a href="https://twitter.com/ctfdio"><i class="fab fa-twitter fa-2x" aria-hidden="true"></i></a>&nbsp;
            <a href="https://facebook.com/ctfdio"><i class="fab fa-facebook fa-2x" aria-hidden="true"></i></a>&nbsp;
            <a href="https://github.com/ctfd"><i class="fab fa-github fa-2x" aria-hidden="true"></i></a>
        </h3>
        <br>
        <h4 class="text-center">
            <a href="admin">Click here</a> to login and setup your CTF
        </h4>
    </div>
</div>""".format(request.script_root)

            page = Pages(
                title=None,
                route='index',
                content=index,
                draft=False
            )
            # Visibility
            set_config('challenge_visibility', 'private')
            set_config('registration_visibility', 'public')
            set_config('score_visibility', 'public')
            set_config('account_visibility', 'public')

            # Start time
            set_config('start', None)
            set_config('end', None)
            set_config('freeze', None)

            # Verify emails
            set_config('verify_emails', None)

            set_config('mail_server', None)
            set_config('mail_port', None)
            set_config('mail_tls', None)
            set_config('mail_ssl', None)
            set_config('mail_username', None)
            set_config('mail_password', None)
            set_config('mail_useauth', None)

            setup = set_config('setup', True)

            try:
                db.session.add(admin)
                db.session.commit()
            except IntegrityError:
                db.session.rollback()

            try:
                db.session.add(page)
                db.session.commit()
            except IntegrityError:
                db.session.rollback()

            login_user(admin)

            db.session.close()
            app.setup = False
            with app.app_context():
                cache.clear()

            return redirect(url_for('views.static_html'))
        return render_template('setup.html', nonce=session.get('nonce'))
    return redirect(url_for('views.static_html'))


@views.route('/notifications', methods=['GET'])
def notifications():
    notifications = Notifications.query.order_by(Notifications.id.desc()).all()
    return render_template('notifications.html', notifications=notifications)


@views.route('/settings', methods=['GET'])
@authed_only
def settings():
    user = get_current_user()
    name = user.name
    email = user.email
    website = user.website
    affiliation = user.affiliation
    country = user.country
    prevent_name_change = get_config('prevent_name_change')
    confirm_email = get_config('verify_emails') and not user.verified
    return render_template(
        'settings.html',
        name=name,
        email=email,
        website=website,
        affiliation=affiliation,
        country=country,
        prevent_name_change=prevent_name_change,
        confirm_email=confirm_email
    )


@views.route('/static/user.css')
def custom_css():
    """
    Custom CSS Handler route
    :return:
    """
    return Response(get_config('css'), mimetype='text/css')


@views.route("/", defaults={'route': 'index'})
@views.route("/<path:route>")
def static_html(route):
    """
    Route in charge of routing users to Pages.
    :param route:
    :return:
    """
    page = get_page(route)
    if page is None:
        abort(404)
    else:
        if page.auth_required and authed() is False:
            return redirect(url_for('auth.login', next=request.full_path))

        return render_template('page.html', content=markdown(page.content))


@views.route('/files', defaults={'path': ''})
@views.route('/files/<path:path>')
def files(path):
    """
    Route in charge of dealing with making sure that CTF challenges are only accessible during the competition.
    :param path:
    :return:
    """
    f = Files.query.filter_by(location=path).first_or_404()
    if f.type == 'challenge':
        if challenges_visible():
            if current_user.is_admin() is False:
                if not ctftime():
                    abort(403)
        else:
            abort(403)

    uploader = get_uploader()
    try:
        return uploader.download(f.location)
    except IOError:
        abort(404)


@views.route('/themes/<theme>/static/<path:path>')
def themes(theme, path):
    """
    General static file handler
    :param theme:
    :param path:
    :return:
    """
    filename = safe_join(app.root_path, 'themes', theme, 'static', path)
    if os.path.isfile(filename):
        return send_file(filename)
    else:
        abort(404)

CTFd/themes/core/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{{ get_ctf_name() }}</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" href="{{ url_for('views.themes', path='img/favicon.ico') }}"
		  type="image/x-icon">
	<link rel="stylesheet" href="{{ url_for('views.themes', path='css/vendor/bootstrap.min.css') }}">
	<link rel="stylesheet" href="{{ url_for('views.themes', path='css/vendor/font-awesome/fontawesome-fonts.css') }}" type='text/css'>
	<link rel="stylesheet" href="{{ url_for('views.themes', path='css/vendor/font-awesome/fontawesome-all.min.css') }}" type='text/css'>
	<link rel="stylesheet" href="{{ url_for('views.themes', path='css/vendor/font.css') }}"  type='text/css'>
	<link rel="stylesheet" href="{{ url_for('views.themes', path='css/jumbotron.css') }}">
	<link rel="stylesheet" href="{{ url_for('views.themes', path='css/sticky-footer.css') }}">
	<link rel="stylesheet" href="{{ url_for('views.themes', path='css/base.css') }}">
	{% block stylesheets %}{% endblock %}
	{% for stylesheet in get_registered_stylesheets() %}
		{% if stylesheet.startswith('http') %}
			<link rel="stylesheet" type="text/css" href="{{ stylesheet }}">
		{% elif request.script_root %}
			<link rel="stylesheet" type="text/css" href="{{ request.script_root }}/{{ stylesheet }}">
		{% else %}
			<link rel="stylesheet" type="text/css" href="{{ stylesheet }}">
		{% endif %}
	{% endfor %}
	<link rel="stylesheet" type="text/css" href="{{ url_for('views.custom_css') }}">
	<script src="{{ url_for('views.themes', path='js/vendor/promise-polyfill.min.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/vendor/fetch.min.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/CTFd.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/vendor/moment.min.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/vendor/nunjucks.min.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/vendor/socket.io.min.js') }}"></script>
	<script type="text/javascript">
		var script_root = "{{ request.script_root }}";
		var csrf_nonce = "{{ nonce }}";
		var user_mode = "{{ get_config('user_mode') }}";
		CTFd.options.urlRoot = script_root;
		CTFd.options.csrfNonce = csrf_nonce;
	</script>
</head>
<body>
	<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
		<div class="container">
			<a href="{{ url_for('views.static_html', route='/') }}" class="navbar-brand">
				{% if get_ctf_logo() %}
				<img class="img-responsive ctf_logo" src="{{ url_for('views.files', path=get_ctf_logo()) }}" height="25" alt="{{ get_ctf_name() }}">
				{% else %}
				{{ get_ctf_name() }}
				{% endif %}
			</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#base-navbars"
					aria-controls="base-navbars" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="base-navbars">
				<ul class="navbar-nav mr-auto">
					{% for page in get_user_page_menu_bar() %}
						{% if page.route.startswith('http://') or page.route.startswith('https://') %}
							<li class="nav-item">
								<a class="nav-link" href="{{ page.route }}">{{ page.title }}</a>
							</li>
						{% else %}
							<li class="nav-item">
								<a class="nav-link" href="{{ url_for('views.static_html', route=page.route) }}">{{ page.title }}</a>
							</li>
						{% endif %}
					{% endfor %}

					<li class="nav-item">
						<a class="nav-link" href="{{ url_for('views.notifications') }}">Notifications</a>
					</li>
					{% if get_config('account_visibility') != 'admins' %}
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('users.listing') }}">Users</a>
						</li>
						{% if get_config('user_mode') == 'teams' %}
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('teams.listing') }}">Teams</a>
						</li>
						{% endif %}
					{% endif %}
					{% if get_config('score_visibility') != 'admins' %}
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('scoreboard.listing') }}">Scoreboard</a>
						</li>
					{% endif %}
					<li class="nav-item">
						<a class="nav-link" href="{{ url_for('challenges.listing') }}">Challenges</a>
					</li>
				</ul>

				<hr class="d-sm-flex d-md-flex d-lg-none">

				<ul class="navbar-nav ml-md-auto d-block d-sm-flex d-md-flex">
					{% if name is defined %}
						{% if type == 'admin' %}
							<li class="nav-item">
								<a class="nav-link" href="{{ url_for('admin.view') }}">Admin</a>
							</li>
						{% endif %}
						{% if config.user_mode() == "teams" %}
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('teams.private') }}">Team</a>
						</li>
						{% endif %}
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('users.private') }}">Profile</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('views.settings') }}">Settings</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
						</li>
					{% else %}
						{% if registration_visible() %}
							<li class="nav-item">
								<a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
							</li>
							<li class="nav-item">
								<a class="nav-link d-none d-md-block d-lg-block">|</a>
							</li>
						{% endif %}
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
						</li>
					{% endif %}
				</ul>
			</div>
		</div>
	</nav>

	<main role="main">
		{% block content %}
		{% endblock %}
	</main>

	<footer class="footer">
		<div class="container text-center">
			<a href="https://ctfd.io">
				<small class="text-muted">Powered by CTFd</small>
			</a>
		</div>
	</footer>

	<script src="{{ url_for('views.themes', path='js/vendor/jquery.min.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/vendor/markdown-it.min.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/vendor/bootstrap.bundle.min.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/style.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/utils.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/ezq.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/events.js') }}"></script>
	{% block scripts %}
	{% endblock %}

	{% for script in get_registered_scripts() %}
	{% if script.startswith('http') %}
	<script src="{{ script }}"></script>
	{% elif request.script_root %}
	<script src="{{ request.script_root }}/{{ script }}"></script>
	{% else %}
	<script src="{{ script }}"></script>
	{% endif %}
	{% endfor %}
</body>
</html>

CTFd/themes/core/templates/challenges.html
{% extends "base.html" %}

{% block stylesheets %}
	<link rel="stylesheet" href="{{ url_for('views.themes', path='css/challenge-board.css') }}">
{% endblock %}

{% block content %}

<div class="jumbotron">
	<div class="container">
		<h1>Challenges</h1>
	</div>
</div>

{% if infos %}
	<div class="container">
		<div id='errors' class="row">
			<div class="col-md-12">
				{% for info in infos %}
					<h1 class="text-center">{{ info }}</h1>
				{% endfor %}
			</div>
		</div>
	</div>
{% endif %}

{% if errors %}
<div class="container">
	<div id='errors' class="row">
		<div class="col-md-12">
{% for error in errors %}
			<h1 class="text-center">{{ error }}</h1>
{% endfor %}
		</div>
	</div>
</div>
{% endif %}

{% if admin or not errors %}
<div class="container">
	<div id='challenges-board'>
		<div class="text-center">
			<i class="fas fa-circle-notch fa-spin fa-3x fa-fw spinner"></i>
		</div>
	</div>
</div>

<input id="nonce" type="hidden" name="nonce" value="{{ nonce }}">

<div class="modal fade" id="challenge-window" tabindex="-1" role="dialog">
</div>
{% endif %}
{% endblock %}

{% block scripts %}
	<script>
		var authed = {{ (id is defined) | tojson }};
	</script>
	<script src="{{ url_for('views.themes', path='js/utils.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/multi-modal.js') }}"></script>
	{% if admin or not errors %}
	<script src="{{ url_for('views.themes', path='js/challenges.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/hints.js') }}"></script>
	{% endif %}
	<script src="{{ url_for('views.themes', path='js/style.js') }}"></script>
{% endblock %}

CTFd/themes/core/templates/confirm.html
{% extends "base.html" %}

{% block stylesheets %}
{% endblock %}

{% block content %}
	<div class="jumbotron">
		<div class="container">
			<h1>Confirm</h1>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-6 offset-md-3">
				{% for info in infos %}
					<div class="alert alert-info alert-dismissable" role="alert">
						<span class="sr-only"></span>
						{{ info }}
						<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
								aria-hidden="true">×</span></button>
					</div>
				{% endfor %}
				{% for error in errors %}
					<div class="alert alert-danger alert-dismissable" role="alert">
						<span class="sr-only">Error:</span>
						{{ error }}
						<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
								aria-hidden="true">×</span></button>
					</div>
				{% endfor %}
				{% if user %}
				<h3 class="text-center">
					We've sent a confirmation email to {{ user.email }}
				</h3>

				<br>

				<h4 class="text-center">
					Please click the link in that email to confirm your account.
				</h4>
				{% endif %}

				<hr>

				{% if name %}
				<form method="POST" action="{{ url_for('auth.confirm') }}">
					<h4 class="text-center">
						Need to resend the confirmation email?
					</h4>
					<div class="col-md-12 text-center">
						<button type="submit" id="submit" tabindex="5" class="btn btn-md btn-primary btn-outlined">Resend</button>
					</div>
					<input type="hidden" name="nonce" value="{{ nonce }}">
				</form>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

{% block scripts %}
	<script src="{{ url_for('views.themes', path='js/style.js') }}"></script>
{% endblock %}

CTFd/themes/core/templates/login.html
{% extends "base.html" %}

{% block stylesheets %}
{% endblock %}

{% block content %}
<div class="jumbotron">
	<div class="container">
		<h1>Login</h1>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-6 offset-md-3">
			{% for error in errors %}
				<div class="alert alert-danger alert-dismissable" role="alert">
				  <span class="sr-only">Error:</span>
				  {{ error }}
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
				</div>
			{% endfor %}

			<a class="btn btn-secondary btn-lg btn-block" href="{{ url_for('auth.oauth_login') }}">Login with Major
				League Cyber</a>

			<hr>

			<form method="post" accept-charset="utf-8" autocomplete="off" role="form" class="form-horizontal">
				<div class="form-group">
					<label for="name-input">
						User Name or Email
					</label>
					<input class="form-control" type="text" name="name" id="name-input" />
				</div>
				<div class="form-group">
					<label for="password-input">
						Password
					</label>
					<input class="form-control" type="password" name="password" id="password-input" />
				</div>
				<div class="row pt-3">
					<div class="col-md-6">
						<a class="float-left align-text-to-button" href="{{ url_for('auth.reset_password') }}">
							Forgot your password?
						</a>
					</div>
					<div class="col-md-6">
						<button type="submit" id="submit" tabindex="5" class="btn btn-md btn-primary btn-outlined float-right">
							Submit
						</button>
					</div>
				</div>
				<input type="hidden" name="nonce" value="{{ nonce }}">
			</form>
		</div>
	</div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

CTFd/themes/core/templates/notifications.html
{% extends "base.html" %}

{% block content %}
	<div class="jumbotron">
		<div class="container">
			<h1>Notifications</h1>
		</div>
	</div>
	<div class="container">
		{% for notification in notifications %}
		<div class="card bg-light mb-4">
			<div class="card-body">
				<h3 class="card-title">{{ notification.title }}</h3>
				<blockquote class="blockquote mb-0">
					<p>{{ notification.content | safe }}</p>
					<small class="text-muted">{{ notification.date | isoformat }}</small>
				</blockquote>
			</div>
		</div>
		{% endfor %}
	</div>
{% endblock %}

{% block scripts %}
	<script src="{{ url_for('views.themes', path='js/vendor/plotly.min.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/utils.js') }}"></script>
{% endblock %}

CTFd/themes/core/templates/page.html
{% extends "base.html" %}

{% block content %}
	<div class="container">
	{{ content | safe }}
	</div>
{% endblock %}

CTFd/themes/core/templates/reset_password.html
{% extends "base.html" %}

{% block stylesheets %}
{% endblock %}

{% block content %}
<div class="jumbotron">
	<div class="container">
		<h1>Reset Password</h1>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-6 offset-md-3">
			{% for error in errors %}
				<div class="alert alert-info alert-dismissable" role="alert">
				  <span class="sr-only">Error:</span>
				  {{ error }}
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
				</div>
			{% endfor %}
			{% if can_send_mail() %}
			<form method="post" accept-charset="utf-8" autocomplete="off" role="form" class="form-horizontal">
				<input name='nonce' type='hidden' value="{{ nonce }}">
				{% if mode %}
				<div class="form-group">
					<label for="password-input">
						Password
					</label>
					<input class="form-control" type="password" name="password" id="password-input" />
				</div>
				{% else %}
				<div class="form-group">
					<label for="email-input">
						Email
					</label>
					<input class="form-control" type="text" name="email" id="email-input" />
				</div>
				{% endif %}
				<div class="row">
					<div class="col-md-6 offset-md-6">
						<button type="submit" id="submit" tabindex="5" class="btn btn-md btn-primary float-right">Submit</button>
					</div>
				</div>
			</form>
			{% else %}
				<h3 class="text-center">Contact a CTF organizer</h3>
				<p>This CTF is not configured to send email.</p>
				<p>Please contact an organizer to have your password reset</p>
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}

{% block scripts %}
	<script src="{{ url_for('views.themes', path='js/style.js') }}"></script>
{% endblock %}