CTFd/admin/__init__.py
from flask import (
    current_app as app,
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    abort,
    render_template_string,
    send_file
)

from CTFd.utils.decorators import admins_only
from CTFd.utils.user import is_admin
from CTFd.utils.security.auth import logout_user
from CTFd.utils.config import is_setup
from CTFd.utils import (
    config as ctf_config,
    validators,
    uploads,
    user as current_user,
    get_config,
    get_app_config,
    set_config,
)
from CTFd.cache import cache, clear_config
from CTFd.utils.helpers import get_errors
from CTFd.utils.exports import (
    export_ctf as export_ctf_util,
    import_ctf as import_ctf_util
)
from CTFd.models import (
    db,
    get_class_by_tablename,
    Users,
    Teams,
    Configs,
    Submissions,
    Solves,
    Awards,
    Unlocks,
    Tracking
)
import datetime
import os
import six
import csv


admin = Blueprint('admin', __name__)


from CTFd.admin import challenges
from CTFd.admin import pages
from CTFd.admin import scoreboard
from CTFd.admin import statistics
from CTFd.admin import teams
from CTFd.admin import users
from CTFd.admin import submissions
from CTFd.admin import notifications


@admin.route('/admin', methods=['GET'])
def view():
    if is_admin():
        return redirect(url_for('admin.statistics'))
    return redirect(url_for('auth.login'))


@admin.route('/admin/plugins/<plugin>', methods=['GET', 'POST'])
@admins_only
def plugin(plugin):
    if request.method == 'GET':
        plugins_path = os.path.join(app.root_path, 'plugins')

        config_html_plugins = [name for name in os.listdir(plugins_path)
                               if os.path.isfile(os.path.join(plugins_path, name, 'config.html'))]

        if plugin in config_html_plugins:
            config_html = open(os.path.join(app.root_path, 'plugins', plugin, 'config.html')).read()
            return render_template_string(config_html)
        abort(404)
    elif request.method == 'POST':
        for k, v in request.form.items():
            if k == "nonce":
                continue
            set_config(k, v)
        with app.app_context():
            clear_config()
        return '1'


@admin.route('/admin/import', methods=['POST'])
@admins_only
def import_ctf():
    backup = request.files['backup']
    segments = request.form.get('segments')
    errors = get_errors()
    try:
        import_ctf_util(backup)
    except Exception as e:
        print(e)
        errors.append(repr(e))

    if errors:
        return errors[0], 500
    else:
        return redirect(url_for('admin.config'))


@admin.route('/admin/export', methods=['GET', 'POST'])
@admins_only
def export_ctf():
    backup = export_ctf_util()
    ctf_name = ctf_config.ctf_name()
    day = datetime.datetime.now().strftime("%Y-%m-%d")
    full_name = u"{}.{}.zip".format(ctf_name, day)
    return send_file(backup, as_attachment=True, attachment_filename=full_name)


@admin.route('/admin/export/csv')
@admins_only
def export_csv():
    table = request.args.get('table')

    # TODO: It might make sense to limit dumpable tables. Config could potentially leak sensitive information.
    model = get_class_by_tablename(table)
    if model is None:
        abort(404)

    output = six.StringIO()
    writer = csv.writer(output)

    header = [column.name for column in model.__mapper__.columns]
    writer.writerow(header)

    responses = model.query.all()

    for curr in responses:
        writer.writerow([getattr(curr, column.name) for column in model.__mapper__.columns])

    output.seek(0)
    return send_file(
        output,
        as_attachment=True,
        cache_timeout=-1,
        attachment_filename="{name}-{table}.csv".format(name=ctf_config.ctf_name(), table=table)
    )


@admin.route('/admin/config', methods=['GET', 'POST'])
@admins_only
def config():
    # Clear the config cache so that we don't get stale values
    clear_config()

    database_tables = sorted(db.metadata.tables.keys())

    configs = Configs.query.all()
    configs = dict([(c.key, get_config(c.key)) for c in configs])

    themes = ctf_config.get_themes()
    themes.remove(get_config('ctf_theme'))

    return render_template(
        'admin/config.html',
        database_tables=database_tables,
        themes=themes,
        **configs
    )


@admin.route('/admin/reset', methods=['GET', 'POST'])
@admins_only
def reset():
    if request.method == 'POST':
        # Truncate Users, Teams, Submissions, Solves, Notifications, Awards, Unlocks, Tracking
        Tracking.query.delete()
        Solves.query.delete()
        Submissions.query.delete()
        Awards.query.delete()
        Unlocks.query.delete()
        Users.query.delete()
        Teams.query.delete()
        set_config('setup', False)
        db.session.commit()
        cache.clear()
        logout_user()
        db.session.close()
        return redirect(url_for('views.setup'))

    return render_template('admin/reset.html')

CTFd/utils/config/__init__.py
from flask import current_app as app
from CTFd.models import Configs, Users, Teams
from CTFd.cache import cache
from CTFd.utils import get_config
from CTFd.utils.user import authed
import time
import os


def ctf_name():
    name = get_config('ctf_name')
    return name if name else 'CTFd'


def user_mode():
    return get_config('user_mode')


def ctf_logo():
    return get_config('ctf_logo')


def ctf_theme():
    theme = get_config('ctf_theme')
    return theme if theme else ''


def is_setup():
    return get_config('setup')


def is_scoreboard_frozen():
    freeze = get_config('freeze')

    if freeze:
        freeze = int(freeze)
        if freeze < time.time():
            return True

    return False


def can_send_mail():
    return mailserver() or mailgun()


def get_mail_provider():
    if app.config.get('MAIL_SERVER') and app.config.get('MAIL_PORT'):
        return 'smtp'
    if get_config('mail_server') and get_config('mail_port'):
        return 'smtp'
    if app.config.get('MAILGUN_API_KEY') and app.config.get('MAILGUN_BASE_URL'):
        return 'mailgun'
    if get_config('mailgun_api_key') and get_config('mailgun_base_url'):
        return 'mailgun'


def mailgun():
    if app.config.get('MAILGUN_API_KEY') and app.config.get('MAILGUN_BASE_URL'):
        return True
    if get_config('mailgun_api_key') and get_config('mailgun_base_url'):
        return True
    return False


def mailserver():
    if app.config.get('MAIL_SERVER') and app.config.get('MAIL_PORT'):
        return True
    if get_config('mail_server') and get_config('mail_port'):
        return True
    return False


def get_themes():
    dir = os.path.join(app.root_path, 'themes')
    return [name for name in os.listdir(dir) if os.path.isdir(os.path.join(dir, name)) and name != 'admin']

CTFd/views.py
from flask import current_app as app, render_template, request, redirect, abort, url_for, session, Blueprint, Response, send_file
from flask.helpers import safe_join

from CTFd.models import db, Admins, Files, Pages, Notifications
from CTFd.utils import markdown
from CTFd.cache import cache
from CTFd.utils import get_config, set_config
from CTFd.utils.user import authed, get_current_user
from CTFd.utils import config
from CTFd.utils.uploads import get_uploader
from CTFd.utils.config.pages import get_page
from CTFd.utils.config.visibility import challenges_visible
from CTFd.utils.security.auth import login_user
from CTFd.utils.security.csrf import generate_nonce
from CTFd.utils import user as current_user
from CTFd.utils.dates import ctf_started, ctftime
from CTFd.utils.decorators import authed_only
from sqlalchemy.exc import IntegrityError
import os


views = Blueprint('views', __name__)


@views.route('/setup', methods=['GET', 'POST'])
def setup():
    if not config.is_setup():
        if not session.get('nonce'):
            session['nonce'] = generate_nonce()
        if request.method == 'POST':
            ctf_name = request.form['ctf_name']
            set_config('ctf_name', ctf_name)

            # CSS
            set_config('start', '')

            # Admin user
            name = request.form['name']
            email = request.form['email']
            password = request.form['password']
            admin = Admins(
                name=name,
                email=email,
                password=password,
                type='admin',
                hidden=True
            )

            user_mode = request.form['user_mode']

            set_config('user_mode', user_mode)

            # Index page

            index = """<div class="row">
    <div class="col-md-6 offset-md-3">
        <img class="w-100 mx-auto d-block" style="max-width: 500px;padding: 50px;padding-top: 14vh;" src="themes/core/static/img/logo.png" />
        <h3 class="text-center">
            <p>A cool CTF platform from <a href="https://ctfd.io">ctfd.io</a></p>
            <p>Follow us on social media:</p>
            <a href="https://twitter.com/ctfdio"><i class="fab fa-twitter fa-2x" aria-hidden="true"></i></a>&nbsp;
            <a href="https://facebook.com/ctfdio"><i class="fab fa-facebook fa-2x" aria-hidden="true"></i></a>&nbsp;
            <a href="https://github.com/ctfd"><i class="fab fa-github fa-2x" aria-hidden="true"></i></a>
        </h3>
        <br>
        <h4 class="text-center">
            <a href="admin">Click here</a> to login and setup your CTF
        </h4>
    </div>
</div>""".format(request.script_root)

            page = Pages(
                title=None,
                route='index',
                content=index,
                draft=False
            )
            # Visibility
            set_config('challenge_visibility', 'private')
            set_config('registration_visibility', 'public')
            set_config('score_visibility', 'public')
            set_config('account_visibility', 'public')

            # Start time
            set_config('start', None)
            set_config('end', None)
            set_config('freeze', None)

            # Verify emails
            set_config('verify_emails', None)

            set_config('mail_server', None)
            set_config('mail_port', None)
            set_config('mail_tls', None)
            set_config('mail_ssl', None)
            set_config('mail_username', None)
            set_config('mail_password', None)
            set_config('mail_useauth', None)

            setup = set_config('setup', True)

            try:
                db.session.add(admin)
                db.session.commit()
            except IntegrityError:
                db.session.rollback()

            try:
                db.session.add(page)
                db.session.commit()
            except IntegrityError:
                db.session.rollback()

            login_user(admin)

            db.session.close()
            app.setup = False
            with app.app_context():
                cache.clear()

            return redirect(url_for('views.static_html'))
        return render_template('setup.html', nonce=session.get('nonce'))
    return redirect(url_for('views.static_html'))


@views.route('/notifications', methods=['GET'])
def notifications():
    notifications = Notifications.query.order_by(Notifications.id.desc()).all()
    return render_template('notifications.html', notifications=notifications)


@views.route('/settings', methods=['GET'])
@authed_only
def settings():
    user = get_current_user()
    name = user.name
    email = user.email
    website = user.website
    affiliation = user.affiliation
    country = user.country
    prevent_name_change = get_config('prevent_name_change')
    confirm_email = get_config('verify_emails') and not user.verified
    return render_template(
        'settings.html',
        name=name,
        email=email,
        website=website,
        affiliation=affiliation,
        country=country,
        prevent_name_change=prevent_name_change,
        confirm_email=confirm_email
    )


@views.route('/static/user.css')
def custom_css():
    """
    Custom CSS Handler route
    :return:
    """
    return Response(get_config('css'), mimetype='text/css')


@views.route("/", defaults={'route': 'index'})
@views.route("/<path:route>")
def static_html(route):
    """
    Route in charge of routing users to Pages.
    :param route:
    :return:
    """
    page = get_page(route)
    if page is None:
        abort(404)
    else:
        if page.auth_required and authed() is False:
            return redirect(url_for('auth.login', next=request.full_path))

        return render_template('page.html', content=markdown(page.content))


@views.route('/files', defaults={'path': ''})
@views.route('/files/<path:path>')
def files(path):
    """
    Route in charge of dealing with making sure that CTF challenges are only accessible during the competition.
    :param path:
    :return:
    """
    f = Files.query.filter_by(location=path).first_or_404()
    if f.type == 'challenge':
        if challenges_visible():
            if current_user.is_admin() is False:
                if not ctftime():
                    abort(403)
        else:
            abort(403)

    uploader = get_uploader()
    try:
        return uploader.download(f.location)
    except IOError:
        abort(404)


@views.route('/themes/<theme>/static/<path:path>')
def themes(theme, path):
    """
    General static file handler
    :param theme:
    :param path:
    :return:
    """
    filename = safe_join(app.root_path, 'themes', theme, 'static', path)
    if os.path.isfile(filename):
        return send_file(filename)
    else:
        abort(404)

CTFd/themes/admin/templates/configs/accounts.html
<div role="tabpanel" class="tab-pane config-section" id="accounts">
	<form method="POST" autocomplete="off" class="w-100">

		<div class="form-group">
			<label>
				Account Email Whitelist
				<small class="form-text text-muted">
					Comma-seperated email domains which users can register under.
				</small>
			</label>
			<input class="form-control" id='domain-whitelist' name='domain_whitelist' type='text'
				   placeholder=""
				   {% if domain_whitelist is defined and domain_whitelist != None %}value="{{ domain_whitelist }}"{% endif %}>
			<small class="form-text text-muted">
				e.g. ctfd.io,gmail.com,yahoo.com
			</small>
		</div>

		<div class="form-group">
			<label>
				Verify Emails<br>
				<small class="form-text text-muted">
					Control whether users must confirm their email addresses before playing
				</small>
			</label>
			<select class="form-control" name="verify_emails">
				<option value="true" {% if verify_emails == True %}selected{% endif %}>Enabled</option>
				<option value="false" {% if verify_emails == False or verify_emails == None %}selected{% endif %}>Disabled</option>
			</select>
		</div>

		<div class="form-group">
			<label>
				Team Name Changes<br>
				<small class="form-text text-muted">
					Control whether users can change their names
				</small>
			</label>
			<select class="form-control" name="name_changes">
				<option value="true" {% if name_changes == True or name_changes == None %}selected{% endif %}>Enabled</option>
				<option value="false" {% if name_changes == False %}selected{% endif %}>Disabled</option>
			</select>
		</div>

		<button type="submit" class="btn btn-md btn-primary float-right">Update</button>
	</form>
</div>

CTFd/themes/admin/templates/configs/appearance.html
<div role="tabpanel" class="tab-pane config-section active" id="appearance">
	<form id="logo-upload" class="form-upload" method="POST" enctype="multipart/form-data">
		<div class="form-group">
			<label for="ctf_logo">
				Logo
				<small class="form-text text-muted">
					Logo to use for the website instead of a CTF name.
				</small>
			</label>

			{% if ctf_logo %}
				<div class="d-block py-3">
					<img id="ctf_logo_preview" class="img-responsive ctf_logo"
						 src="{{ url_for('views.files', path=ctf_logo) }}"
						 height="25">
					<button type="button" class="btn-sm btn-danger" onclick="remove_logo()">
						Remove Logo
					</button>
				</div>
			{% endif %}

			<div class="row">
				<div class="col-md-9">
					<input class="form-control-file" id="ctf_logo_file" name='file' type='file'
						   placeholder="CTF Logo">
				</div>
				<div class="col-md-3">
					<div class="form-group">
						<div class="d-inline-block float-right">
							<button type="submit" class="btn-sm btn-primary float-right">Upload</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</form>

	<hr>

	<form method="POST" autocomplete="off" class="w-100">
		<div class="form-group">
			<label for="ctf_name">
				Competition Name
				<small class="form-text text-muted">Competition name displayed instead of a logo</small>
			</label>
			<input class="form-control" id='ctf_name' name='ctf_name' type='text' placeholder="CTF Name"
				   {% if ctf_name is defined and ctf_name != None %}value="{{ ctf_name }}"{% endif %}>
		</div>

		<div class="form-group">
			<label for="user_mode">
				User Mode
				<small class="form-text text-muted">User mode allows users to register as themselves
					or choose to form teams.
				</small>
			</label>
			<div data-toggle="tooltip" data-placement="bottom" title="In order to change User Mode you must reset your CTF">
				<select class="form-control" id="user_mode" name="user_mode" disabled="true" style="z-index: -1;">
					<option value="teams" {% if user_mode == 'teams' %}selected{% endif %}>
						Teams
					</option>
					<option value="users" {% if user_mode == 'users' %}selected{% endif %}>
						Users
					</option>
				</select>
			</div>
		</div>

		<div class="form-group">
			<label for="ctf_theme">
				Theme
				<small class="form-text text-muted">
					Switch themes to change CTFd's aesthetics
				</small>
			</label>
			<select class="form-control" id="ctf_theme" name="ctf_theme">
				<option>{{ ctf_theme }}</option>
				{% for theme in themes %}
					<option>{{ theme }}</option>
				{% endfor %}
			</select>
		</div>

		<div class="form-group">
			<label>
				Stylesheet editor
				<small class="form-text text-muted">
					CSS is applied to all public facing pages if the theme used supports custom CSS.
				</small>
			</label>
			<textarea class="form-control" id="css-editor" name="css" rows="7">{{ css }}</textarea>
		</div>

		<button type="submit" class="btn btn-md btn-primary float-right">Update</button>
	</form>
</div>

CTFd/themes/admin/templates/configs/backup.html
<div role="tabpanel" class="tab-pane config-section" id="backup">
	<ul class="nav nav-tabs mb-3" role="tablist">
		<li class="nav-item">
			<a class="nav-link active" href="#export-ctf" aria-controls="export-ctf" role="tab"
			   data-toggle="tab">Export</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="#import-ctf" aria-controls="import-ctf" role="tab" data-toggle="tab">Import</a>
		</li>
		<li class="nav-item">
			<a class="nav-link " href="#save-csv" aria-controls="save-csv" role="tab" data-toggle="tab">Download CSV</a>
		</li>
	</ul>
	<div class="tab-content">
		<div role="tabpanel" class="tab-pane active" id="export-ctf">
			<div class="form-group">
				<p>Exports are an archive of your CTF in its current state. They can be re-imported into other CTFd
					instances or used by scripts and third parties to calculate statistics.</p>
				<p>To download an export click the button below.</p>
			</div>
			<div class="form-group">
				<a href="{{ url_for('admin.export_ctf') }}" id="export-button" class="btn btn-warning">Export</a>
			</div>
		</div>
		<div role="tabpanel" class="tab-pane" id="import-ctf">
			<div class="form-group">
				<p>You can import saved CTFd exports by uploading them below. This will completely wipe your existing
					CTFd instance and all your data will be replaced by the imported data.
					You should only import data that you trust!</p>

				<div class="alert alert-warning" role="alert">
					IMPORTING A CTF WILL COMPLETELY WIPE YOUR EXISTING DATA
				</div>
			</div>
			<div class="form-group">
				<label for="container-files">Import File</label>
				<input class="form-control-file" type="file" name="backup" id="import-file" accept=".zip">
			</div>
			<input id="import-button" type="submit" class="btn btn-warning" value="Import">
		</div>
		<div role="tabpanel" class="tab-pane" id="save-csv">
			<form method="GET" action="{{ url_for('admin.export_csv') }}">
				<div class="form-group">
					<label for="container-files">Database Table</label>
					<select class="form-control" name="table">
						{% for table in database_tables %}
							<option value="{{ table }}">{{ table }}</option>
						{% endfor %}
					</select>
				</div>
				<input type="submit" class="btn btn-warning" value="Download CSV">
			</form>
		</div>
	</div>
</div>

CTFd/themes/admin/templates/configs/email.html
<div role="tabpanel" class="tab-pane config-section" id="email">
	<form method="POST" autocomplete="off" class="w-100">
		<ul class="nav nav-tabs mb-3" role="tablist">
			<li class="nav-item active">
				<a class="nav-link active" href="#mailserver" role="tab" data-toggle="tab">Mail
					Server</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#mailgun" role="tab" data-toggle="tab">Mailgun</a>
			</li>
		</ul>

		<div class="form-group">
			<label>
				Mail From Address<br>
				<small class="form-text text-muted">
					Email address used to send email
				</small>
			</label>
			<input class="form-control" id='mailfrom_addr' name='mailfrom_addr' type='text' {% if mailfrom_addr is defined and mailfrom_addr != None %}value="{{ mailfrom_addr }}"{% endif %}>
		</div>

		<div class="tab-content">
			<div role="tabpanel" class="tab-pane active" id="mailserver">

				<div class="form-group">
					<label>
						Mail Server Address<br>
						<small class="form-text text-muted">
							Mail Server Address
						</small>
					</label>
					<input class="form-control" id='mail_server' name='mail_server' type='text'
						   {% if mail_server is defined and mail_server != None %}value="{{ mail_server }}"{% endif %}>
				</div>

				<div class="form-group">
					<label>
						Mail Server Port<br>
						<small class="form-text text-muted">
							Mail Server Port
						</small>
					</label>
					<input class="form-control" id='mail_port' name='mail_port' type='text'
						   {% if mail_port is defined and mail_port != None %}value="{{ mail_port }}"{% endif %}>
				</div>
				<div class="form-check">
					<label>
						<input id="mail_useauth" name="mail_useauth" type="checkbox"
							   {% if mail_useauth %}checked{% endif %}>
						Use Mail Server Username and Password
					</label>
				</div>
				<div id="mail_username_password">
					<div class="form-group">
						<label>
							Username<br>
							<small class="form-text text-muted">
								Mail Server Account Username
							</small>
						</label>
						{% if mail_username is defined and mail_username != None %}
							<label>
								<sup class="form-text text-muted">A mail server username is currently set</sup>
							</label>
						{% endif %}
						<input class="form-control" id='mail_username' name='mail_username' autocomplete='off' type='text'>
					</div>
					<div class="form-group">
						<label for="mail_password">
							Password<br>
							<small class="form-text text-muted">
								Mail Server Account Password
							</small>
						</label>
						{% if mail_password is defined and mail_password != None %}
							<label>
								<sup class="form-text text-muted">An mail server password is currently set</sup>
							</label>
						{% endif %}
						<input class="form-control" id='mail_password' name='mail_password' autocomplete='off' type='password'>
					</div>
					<sup>Uncheck setting and update to remove username and password</sup>
					<br>
					<br>
				</div>
				<div class="form-check">
					<label>
						<input id="mail_ssl" name="mail_ssl" type="checkbox" {% if mail_ssl %}checked{% endif %}>
						SSL
					</label>
				</div>
				<div class="form-check">
					<label>
						<input id="mail_tls" name="mail_tls" type="checkbox" {% if mail_tls %}checked{% endif %}>
						TLS
					</label>
				</div>
			</div>
			<div role="tabpanel" class="tab-pane" id="mailgun">
				<div class="form-group">
					<label>
						Mailgun API Base URL<br>
						<small class="form-text text-muted">
							Mailgun API Base URL
						</small>
					</label>
					<input class="form-control" id='mailgun_base_url' name='mailgun_base_url' type='text'
						   {% if mailgun_base_url is defined and mailgun_base_url != None %}value="{{ mailgun_base_url }}"{% endif %}>
				</div>
				<div class="form-group">
					<label>
						Mailgun API Key<br>
						<small class="form-text text-muted">
							Mailgun API Key
						</small>
					</label>
					<input class="form-control" id='mailgun_api_key' name='mailgun_api_key' type='text'
						   {% if mailgun_api_key is defined and mailgun_api_key != None %}value="{{ mailgun_api_key }}"{% endif %}>
				</div>
			</div>
		</div>
		<button type="submit" class="btn btn-md btn-primary float-right">Update</button>
	</form>
</div>

CTFd/themes/admin/templates/configs/mlc.html
<div role="tabpanel" class="tab-pane config-section" id="mlc">
	<form method="POST" autocomplete="off" class="w-100">

		<div class="form-group">
			<label>
				Client ID
				<small class="form-text text-muted">
					OAuth Client ID for <a href="https://majorleaguecyber.org/">MajorLeagueCyber</a> integration.
				</small>
			</label>
			<input class="form-control" id='oauth_client_id' name='oauth_client_id' type='text'
				   placeholder=""
				   {% if oauth_client_id is defined and oauth_client_id != None %}value="{{ oauth_client_id }}"{% endif %}>
		</div>

		<div class="form-group">
			<label>
				Client Secret
				<small class="form-text text-muted">
					OAuth Client Secret for <a href="https://majorleaguecyber.org/">MajorLeagueCyber</a> integration.
				</small>
			</label>
			<input class="form-control" id='oauth_client_secret' name='oauth_client_secret' type='text'
				   placeholder=""
				   {% if oauth_client_secret is defined and oauth_client_secret != None %}value="{{ oauth_client_secret }}"{% endif %}>
		</div>

		<button type="submit" class="btn btn-md btn-primary float-right">Update</button>
	</form>
</div>

CTFd/themes/admin/templates/configs/settings.html
<div role="tabpanel" class="tab-pane config-section" id="settings">
	<form method="POST" autocomplete="off" class="w-100">
		<div class="form-group">
			<label>
				Challenge Visibility<br>
				<small class="form-text text-muted">
					Control whether users must be logged in to see challenges
				</small>
			</label>
			<select class="form-control" name="challenge_visibility">
				<option value="public" {% if challenge_visibility == 'public' %}selected{% endif %}>
					Public
				</option>
				<option value="private" {% if challenge_visibility == 'private' %}selected{% endif %}>
					Private
				</option>
			</select>
		</div>

		<div class="form-group">
			<label>
				Score Visibility<br>
				<small class="form-text text-muted">
					Control whether solves/score are shown to the public, to logged in users, hidden to all non-admins, or only shown to admins
				</small>
			</label>
			<select class="form-control" name="score_visibility">
				<option value="public" {% if score_visibility == 'public' %}selected{% endif %}>
					Public
				</option>
				<option value="private" {% if score_visibility == 'private' %}selected{% endif %}>
					Private
				</option>
				<option value="hidden" {% if score_visibility == 'hidden' %}selected{% endif %}>
					Hidden
				</option>
				<option value="admins" {% if score_visibility == 'admins' %}selected{% endif %}>
					Admins Only
				</option>
			</select>
			<small class="form-text text-muted">
				This setting should generally be the same as Account Visibility to avoid conflicts.
			</small>
		</div>

		<div class="form-group">
			<label>
				Account Visibility<br>
				<small class="form-text text-muted">
					Control whether accounts (users &amp; teams) are shown to everyone or only to admins
				</small>
			</label>
			<select class="form-control" name="account_visibility">
				<option value="public" {% if account_visibility == 'public' %}selected{% endif %}>
					Public
				</option>
				<option value="private" {% if account_visibility == 'private' %}selected{% endif %}>
					Private
				</option>
				<option value="admins" {% if account_visibility == 'admins' %}selected{% endif %}>
					Admins Only
				</option>
			</select>
			<small class="form-text text-muted">
				This setting should generally be the same as Score Visibility to avoid conflicts.
			</small>
		</div>

		<div class="form-group">
			<label>
				Registration Visibility<br>
				<small class="form-text text-muted">
					Control whether registration is enabled for everyone or disabled
				</small>
			</label>
			<select class="form-control" name="registration_visibility">
				<option value="public" {% if registration_visibility == 'public' %}selected{% endif %}>
					Public
				</option>
				<option value="private" {% if registration_visibility == 'private' %}selected{% endif %}>
					Private
				</option>
			</select>
		</div>

		<div class="form-group">
			<div class="form-check">
				<label>
					<input id="paused" name="paused" type="checkbox" {% if paused %}checked{% endif %}>
					Pause CTF<br>
					<small>
						Prevent users from submitting answers until unpaused. Challenges can still be viewed.
					</small>
				</label>
			</div>
		</div>

		<button type="submit" class="btn btn-md btn-primary float-right">Update</button>
	</form>
</div>